[project]
name = "market-data-collector"
version = "0.1.0"
description = "Market data collection system with WebSocket support"
requires-python = ">=3.8"
dependencies = [
    "PyYAML>=6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
